repos:
-   repo: https://github.com/rOOt-Rajat/Django-Ecommerce.git
    rev: v4.0.1
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
