name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
    - run: pip install virtualenv
    - run: make
    - name: self test newly built action
      uses: ./
    - run: make push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
