name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with:
          python-version: '3.6.9'
          architecture: x64
    - name: check version
      run: |
          pip install -U prospector
          pip freeze | grep 'prospector==' | sed -E 's#(prospector)#\1\[with_everything\]#g' >requirements.txt
    - uses: peter-evans/create-pull-request@v3.10.0
      id: new_pull_request
      with:
        delete-branch: true
        title: automatic prospector update
        commit-message: automatic prospector update
        branch: automatic-prospector-update
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - if: steps.new_pull_request.outputs.pull-request-url != ''
      run: gh pr merge --auto --squash ${{ steps.new_pull_request.outputs.pull-request-url }}
