-name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-18.04
    steps:
    - uses: pre-commit/action@v2.0.3
    - name: Pre-commit autoupdate
    - uses: browniebroke/pre-commit-autoupdate-action@v1.0.0
